// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '',
    appId: '1:167105753746:web:27e34da2dd7c98c461ac4b',
    messagingSenderId: '167105753746',
    projectId: 'remoteor-8dc3a',
    authDomain: 'remoteor-8dc3a.firebaseapp.com',
    storageBucket: 'remoteor-8dc3a.firebasestorage.app',
    measurementId: 'G-0FWPTGD7DP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '',
    appId: '1:167105753746:android:b3bfec2c4c555bc661ac4b',
    messagingSenderId: '167105753746',
    projectId: 'remoteor-8dc3a',
    storageBucket: 'remoteor-8dc3a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '',
    appId: '1:167105753746:ios:56fb2d8edb1bf23361ac4b',
    messagingSenderId: '167105753746',
    projectId: 'remoteor-8dc3a',
    storageBucket: 'remoteor-8dc3a.firebasestorage.app',
    iosBundleId: 'com.example.remoteor',
  );
}
